{
 "title": "SAGE-Container Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/docker/.+\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\".+\"}"
    }
   ]
  }
 ]
}